// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBxijuuJ4VnE1f235PSjfTl2rrJHdL9koM',
//     appId: '1:806975117481:web:ca38c55de14f9caa0531b8',
//     messagingSenderId: '806975117481',
//     projectId: 'fitness-app-73925',
//     authDomain: 'fitness-app-73925.firebaseapp.com',
//     storageBucket: 'fitness-app-73925.firebasestorage.app',
//     measurementId: 'G-ZLK0B4EZ04',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD0FB88mjEWAwGTtxWNnNT723mSAddTFKk',
//     appId: '1:806975117481:android:ab1b48c935856d0e0531b8',
//     messagingSenderId: '806975117481',
//     projectId: 'fitness-app-73925',
//     storageBucket: 'fitness-app-73925.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDqojCqgYw05DTWqWnt9JBCSlCs29k9FEU',
//     appId: '1:806975117481:ios:bdeb64edbadfba340531b8',
//     messagingSenderId: '806975117481',
//     projectId: 'fitness-app-73925',
//     storageBucket: 'fitness-app-73925.firebasestorage.app',
//     iosBundleId: 'com.example.FitTrack',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBxijuuJ4VnE1f235PSjfTl2rrJHdL9koM',
//     appId: '1:806975117481:web:e7e7e4009e00f1b90531b8',
//     messagingSenderId: '806975117481',
//     projectId: 'fitness-app-73925',
//     authDomain: 'fitness-app-73925.firebaseapp.com',
//     storageBucket: 'fitness-app-73925.firebasestorage.app',
//     measurementId: 'G-R0Q7JN1V4G',
//   );
// }
