// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
apiKey: "AIzaSyAwSCbYTc9MZQi9FaPzId6OpZten011aXw",
  authDomain: "fitness-app-4dcc6.firebaseapp.com",
  projectId: "fitness-app-4dcc6",
  storageBucket: "fitness-app-4dcc6.firebasestorage.app",
  messagingSenderId: "701877404173",
  appId: "1:701877404173:web:27c395c8ffc91db089cb44",
  measurementId: "G-4DLXKD05CG"
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: "AIzaSyAwSCbYTc9MZQi9FaPzId6OpZten011aXw",
  authDomain: "fitness-app-4dcc6.firebaseapp.com",
  projectId: "fitness-app-4dcc6",
  storageBucket: "fitness-app-4dcc6.firebasestorage.app",
  messagingSenderId: "701877404173",
  appId: "1:701877404173:android:220905d5bed7778b89cb44",
  measurementId: "G-4DLXKD05CG"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAwSCbYTc9MZQi9FaPzId6OpZten011aXw",
  authDomain: "fitness-app-4dcc6.firebaseapp.com",
  projectId: "fitness-app-4dcc6",
  storageBucket: "fitness-app-4dcc6.firebasestorage.app",
  messagingSenderId: "701877404173",
  appId: "1:701877404173:web:27c395c8ffc91db089cb44",
  measurementId: "G-4DLXKD05CG"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAwSCbYTc9MZQi9FaPzId6OpZten011aXw",
  authDomain: "fitness-app-4dcc6.firebaseapp.com",
  projectId: "fitness-app-4dcc6",
  storageBucket: "fitness-app-4dcc6.firebasestorage.app",
  messagingSenderId: "701877404173",
  appId: "1:701877404173:web:27c395c8ffc91db089cb44",
  measurementId: "G-4DLXKD05CG"
  );
}
